/* Problem Bank — problem list, shared by problem-bank/index.html and every problem page. */
const PROBLEM_BANK = [
  {
    slug: 'implement-trie-prefix-tree',
    title: 'Implement Trie (Prefix Tree)',
    pattern: 'Trie',
    difficulty: 'Medium',
    prereqDay: 19,
    prereqTitle: 'Trees — BFS & DFS',
    leetcodeUrl: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
  },
  {
    slug: 'insert-interval',
    title: 'Insert Interval',
    pattern: 'Intervals',
    difficulty: 'Medium',
    prereqDay: 29,
    prereqTitle: 'Mock Interview Day',
    leetcodeUrl: 'https://leetcode.com/problems/insert-interval/',
  },
  {
    slug: 'lru-cache',
    title: 'LRU Cache',
    pattern: 'Design',
    difficulty: 'Medium',
    prereqDay: 15,
    prereqTitle: 'Linked Lists',
    leetcodeUrl: 'https://leetcode.com/problems/lru-cache/',
  },
  {
    slug: 'combination-sum',
    title: 'Combination Sum',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    prereqDay: 9,
    prereqTitle: 'Recursion & the Call Stack',
    leetcodeUrl: 'https://leetcode.com/problems/combination-sum/',
  },
  {
    slug: 'subsets',
    title: 'Subsets',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    prereqDay: 9,
    prereqTitle: 'Recursion & the Call Stack',
    leetcodeUrl: 'https://leetcode.com/problems/subsets/',
  },
  {
    slug: 'permutations',
    title: 'Permutations',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    prereqDay: 9,
    prereqTitle: 'Recursion & the Call Stack',
    leetcodeUrl: 'https://leetcode.com/problems/permutations/',
  },
  {
    slug: 'generate-parentheses',
    title: 'Generate Parentheses',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    prereqDay: 9,
    prereqTitle: 'Recursion & the Call Stack',
    leetcodeUrl: 'https://leetcode.com/problems/generate-parentheses/',
  },
  {
    slug: 'letter-combinations-of-a-phone-number',
    title: 'Letter Combinations of a Phone Number',
    pattern: 'Backtracking',
    difficulty: 'Medium',
    prereqDay: 9,
    prereqTitle: 'Recursion & the Call Stack',
    leetcodeUrl: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
  },
  {
    slug: 'n-queens',
    title: 'N-Queens',
    pattern: 'Backtracking',
    difficulty: 'Hard',
    prereqDay: 9,
    prereqTitle: 'Recursion & the Call Stack',
    leetcodeUrl: 'https://leetcode.com/problems/n-queens/',
  },
  {
    slug: 'jump-game-ii',
    title: 'Jump Game II',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/jump-game-ii/',
  },
  {
    slug: 'gas-station',
    title: 'Gas Station',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/gas-station/',
  },
  {
    slug: 'candy',
    title: 'Candy',
    pattern: 'Greedy',
    difficulty: 'Hard',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/candy/',
  },
  {
    slug: 'partition-labels',
    title: 'Partition Labels',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/partition-labels/',
  },
  {
    slug: 'valid-parenthesis-string',
    title: 'Valid Parenthesis String',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/valid-parenthesis-string/',
  },
  {
    slug: 'hand-of-straights',
    title: 'Hand of Straights',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/hand-of-straights/',
  },
  {
    slug: 'merge-triplets-to-form-target-triplet',
    title: 'Merge Triplets to Form Target Triplet',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/',
  },
  {
    slug: 'assign-cookies',
    title: 'Assign Cookies',
    pattern: 'Greedy',
    difficulty: 'Easy',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/assign-cookies/',
  },
  {
    slug: 'can-place-flowers',
    title: 'Can Place Flowers',
    pattern: 'Greedy',
    difficulty: 'Easy',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/can-place-flowers/',
  },
  {
    slug: 'boats-to-save-people',
    title: 'Boats to Save People',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/boats-to-save-people/',
  },
  {
    slug: 'two-city-scheduling',
    title: 'Two City Scheduling',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/two-city-scheduling/',
  },
  {
    slug: 'minimum-number-of-arrows-to-burst-balloons',
    title: 'Minimum Number of Arrows to Burst Balloons',
    pattern: 'Greedy',
    difficulty: 'Medium',
    prereqDay: 27,
    prereqTitle: 'Greedy Algorithms',
    leetcodeUrl: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/',
  },
  {
    slug: 'valid-sudoku',
    title: 'Valid Sudoku',
    pattern: 'Arrays & Hashing',
    difficulty: 'Medium',
    prereqDay: 6,
    prereqTitle: 'Hash Maps & Sets',
    leetcodeUrl: 'https://leetcode.com/problems/valid-sudoku/',
  },
  {
    slug: 'first-missing-positive',
    title: 'First Missing Positive',
    pattern: 'Arrays & Hashing',
    difficulty: 'Hard',
    prereqDay: 6,
    prereqTitle: 'Hash Maps & Sets',
    leetcodeUrl: 'https://leetcode.com/problems/first-missing-positive/',
  },
  {
    slug: 'majority-element',
    title: 'Majority Element',
    pattern: 'Arrays & Hashing',
    difficulty: 'Easy',
    prereqDay: 6,
    prereqTitle: 'Hash Maps & Sets',
    leetcodeUrl: 'https://leetcode.com/problems/majority-element/',
  },
  {
    slug: 'maximum-subarray',
    title: 'Maximum Subarray',
    pattern: 'Arrays & Hashing',
    difficulty: 'Medium',
    prereqDay: 6,
    prereqTitle: 'Hash Maps & Sets',
    leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray/',
  },
  {
    slug: 'longest-consecutive-sequence',
    title: 'Longest Consecutive Sequence',
    pattern: 'Arrays & Hashing',
    difficulty: 'Medium',
    prereqDay: 6,
    prereqTitle: 'Hash Maps & Sets',
    leetcodeUrl: 'https://leetcode.com/problems/longest-consecutive-sequence/',
  },
];

const PROBLEM_BANK_PATTERNS = [
  { key: 'Trie', title: 'Trie' },
  { key: 'Intervals', title: 'Intervals' },
  { key: 'Design', title: 'Design' },
  { key: 'Backtracking', title: 'Backtracking' },
  { key: 'Greedy', title: 'Greedy' },
  { key: 'Arrays & Hashing', title: 'Arrays & Hashing' },
];

function problemBankInfo(slug) {
  return PROBLEM_BANK.find((p) => p.slug === slug) || null;
}

// Other problems sharing the same pattern, in PROBLEM_BANK order, wrapping
// around after the given slug so every problem in a pattern gets a varied set
// of neighbors instead of always seeing the same fixed "next 3".
function relatedProblems(slug, limit) {
  const current = problemBankInfo(slug);
  if (!current) return [];
  const samePattern = PROBLEM_BANK.filter((p) => p.pattern === current.pattern && p.slug !== slug);
  const startIndex = PROBLEM_BANK.findIndex((p) => p.slug === slug);
  samePattern.sort((a, b) => {
    const distA = (PROBLEM_BANK.indexOf(a) - startIndex + PROBLEM_BANK.length) % PROBLEM_BANK.length;
    const distB = (PROBLEM_BANK.indexOf(b) - startIndex + PROBLEM_BANK.length) % PROBLEM_BANK.length;
    return distA - distB;
  });
  return samePattern.slice(0, limit);
}
